apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloapp-ui
  template:
    metadata:
      labels:
        app: helloapp-ui
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/jonfrankel-demo-env/quickstart-docker-repo/hello-app@sha256:02d4ba9743557e7c9565e40d21bcf3ea3b857cffeb02460380cf79c8564a46ec
        name: helloapp-ui
        ports:
        - containerPort: 8080
