apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/jonfrankel-demo-env/quickstart-docker-repo/beginner@sha256:10d413b26cb85a8f2ebc2c2365e13572f6781cd5e7590c677d0460f9d74f0882
        name: guestbook-ui
        ports:
        - containerPort: 80
